name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  module-name:  # id of input
    description: 'Module Name'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'